encoder_type: RoPE Encoder
encoder_params:
  n_feats: ${model.n_feats}
  n_channels: 192
  filter_channels: 768
  filter_channels_dp: 256
  n_heads: 2
  n_layers: 6
  kernel_size: 3
  p_dropout: 0.1
  spk_emb_dim: 64
  n_spks: ${data.n_spks}
  prenet: true

  gst_params:
    hidden_size: 128
    num_layers: 1
    out_size: ${model.encoder.encoder_params.n_channels}
    num_units: 384
    num_heads: 8
    token_num: 6
  
duration_predictor_params:
  filter_channels_dp: ${model.encoder.encoder_params.filter_channels_dp}
  kernel_size: 3
  p_dropout: ${model.encoder.encoder_params.p_dropout}
